FROM node:24-bullseye

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json from build context (web/)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code from the web build context
COPY . .

# Build the application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]